# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('cat_descripcion', models.CharField(max_length=150)),
                ('cat_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='basedatos.Catalogo')),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('enc_codigo', models.CharField(max_length=7)),
                ('enc_fecha_mod', models.DateTimeField()),
            ],
            options={
                'db_table': 'encuesta',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id_informacion', models.AutoField(primary_key=True, serialize=False)),
                ('inf_fecha_creacion', models.DateTimeField()),
                ('inf_nombres', models.CharField(max_length=150)),
                ('inf_apellidos', models.CharField(max_length=150)),
                ('inf_fecha_nac', models.DateTimeField()),
                ('inf_telefono', models.CharField(max_length=20)),
                ('inf_direccion', models.CharField(max_length=300)),
                ('inf_personas', models.PositiveSmallIntegerField()),
                ('inf_cloacas', models.BooleanField()),
                ('inf_cbzfam', models.BooleanField()),
                ('inf_ingresos', models.BooleanField()),
                ('inf_llegafin', models.BooleanField()),
                ('inf_trabajo', models.CharField(max_length=150)),
                ('inf_seguro', models.BooleanField()),
                ('inf_det_seguro', models.CharField(max_length=150)),
                ('inf_chequeos', models.BooleanField()),
                ('inf_mes_chequeos', models.PositiveSmallIntegerField()),
                ('inf_vec_chequeos', models.PositiveSmallIntegerField()),
                ('inf_diabetes', models.BooleanField()),
                ('inf_tiempo_diab', models.PositiveSmallIntegerField()),
                ('inf_presion', models.BooleanField()),
                ('inf_enf_renal', models.BooleanField()),
                ('inf_det_renal', models.CharField(max_length=150)),
                ('inf_otra_enf', models.BooleanField()),
                ('inf_det_enf', models.CharField(max_length=150)),
                ('inf_insulina', models.BooleanField()),
                ('inf_hipoglucemias', models.BooleanField()),
                ('inf_det_hipogluce', models.CharField(max_length=150)),
                ('inf_razon_1', models.BooleanField()),
                ('inf_razon_2', models.BooleanField()),
                ('inf_razon_3', models.BooleanField()),
                ('inf_razon_4', models.BooleanField()),
                ('inf_med_presion', models.BooleanField()),
                ('inf_det_med_pre', models.CharField(max_length=150)),
                ('inf_analgesicos', models.BooleanField()),
                ('inf_det_analgesicos', models.CharField(max_length=150)),
                ('inf_med_otros', models.BooleanField()),
                ('inf_det_med_otros', models.CharField(max_length=150)),
                ('inf_med_1', models.BooleanField()),
                ('inf_med_2', models.BooleanField()),
                ('inf_med_3', models.BooleanField()),
                ('inf_glucosa', models.BooleanField()),
                ('inf_dia_familia', models.BooleanField()),
                ('inf_dia_parientes', models.BooleanField()),
                ('inf_ant_embarazo', models.BooleanField()),
                ('inf_peso_hijos', models.BooleanField()),
                ('inf_pre_familia', models.BooleanField()),
                ('inf_renal_familia', models.BooleanField()),
                ('inf_det_renal_fam', models.CharField(max_length=150)),
                ('inf_tabaco', models.BooleanField()),
                ('inf_det_tabaco', models.PositiveSmallIntegerField()),
                ('inf_alcohol', models.BooleanField()),
                ('inf_det_alcohol', models.PositiveSmallIntegerField()),
                ('inf_otros_hab', models.BooleanField()),
                ('inf_det_otro_hab', models.CharField(max_length=150)),
                ('inf_nombre_resp', models.CharField(max_length=150)),
                ('inf_cedula_resp', models.CharField(max_length=10)),
                ('inf_uuid_creado', models.CharField(max_length=36)),
                ('inf_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_agua', to='basedatos.Catalogo')),
            ],
            options={
                'db_table': 'informacion_general',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('lab_fecha_creacion', models.DateTimeField()),
                ('lab_nombres', models.CharField(max_length=150)),
                ('lab_glucosa_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lab_glucosa_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lab_hemo_glico', models.PositiveSmallIntegerField()),
                ('lab_microalbum', models.PositiveSmallIntegerField()),
                ('lab_creatinina', models.PositiveSmallIntegerField()),
                ('lab_filtrado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lab_nombre_resp', models.CharField(max_length=150)),
                ('lab_cedula_resp', models.CharField(max_length=10)),
                ('lab_uuid_creado', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('loc_codigo', models.CharField(max_length=3)),
                ('loc_descripcion', models.CharField(max_length=150)),
                ('loc_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='basedatos.Localidad')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id_medidas', models.AutoField(primary_key=True, serialize=False)),
                ('med_fecha_creacion', models.DateTimeField()),
                ('med_nombres', models.CharField(max_length=150)),
                ('med_peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('med_estatura', models.PositiveSmallIntegerField()),
                ('med_caderas', models.PositiveSmallIntegerField()),
                ('med_cintura', models.PositiveSmallIntegerField()),
                ('med_imc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('med_indice_cc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('med_peso_sal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('med_nombre_resp', models.CharField(max_length=150)),
                ('med_cedula_resp', models.CharField(max_length=10)),
                ('med_uuid_creado', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Preparacion',
            fields=[
                ('id_preparacion', models.AutoField(primary_key=True, serialize=False)),
                ('prep_fecha_creacion', models.DateTimeField()),
                ('prep_nombres', models.CharField(max_length=150)),
                ('prep_ayunas', models.BooleanField(default=False)),
                ('prep_lugar', models.CharField(max_length=150)),
                ('prep_fecha', models.DateField()),
                ('prep_foto_cons', models.ImageField(blank=True, null=True, upload_to='/preparacion/consentimientos')),
                ('prep_nombre_resp', models.CharField(max_length=150)),
                ('prep_cedula_resp', models.CharField(max_length=10)),
                ('prep_uuid_creado', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'preparacion',
            },
        ),
        migrations.CreateModel(
            name='Presion',
            fields=[
                ('id_presion', models.AutoField(primary_key=True, serialize=False)),
                ('pres_fecha_creacion', models.DateTimeField()),
                ('pres_nombres', models.CharField(max_length=150)),
                ('pres_min_1', models.PositiveSmallIntegerField()),
                ('pres_min_2', models.PositiveSmallIntegerField()),
                ('pres_min_3', models.PositiveSmallIntegerField()),
                ('pres_max_1', models.PositiveSmallIntegerField()),
                ('pres_max_2', models.PositiveSmallIntegerField()),
                ('pres_max_3', models.PositiveSmallIntegerField()),
                ('pres_prom_min', models.PositiveSmallIntegerField()),
                ('pres_prom_max', models.PositiveSmallIntegerField()),
                ('pres_nombre_resp', models.CharField(max_length=150)),
                ('pres_cedula_resp', models.CharField(max_length=10)),
                ('pres_uuid_creado', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'presion',
            },
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_canton', to='basedatos.Localidad'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_ejercicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_ejercicios', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_est_civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_estcivil', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_estudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_estudios', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_etnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_etnia', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_ocupacion', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_provincia', to='basedatos.Localidad'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_sexo', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='informacion',
            name='inf_vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestado_vivienda', to='basedatos.Catalogo'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_informacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_informacion', to='basedatos.Informacion'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_laboratorio', to='basedatos.Laboratorio'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_medidas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_medidas', to='basedatos.Medidas'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_preparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_preparacion', to='basedatos.Preparacion'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fk_presion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_presion', to='basedatos.Presion'),
        ),
    ]
