# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('cat_descripcion', models.CharField(max_length=150)),
                ('cat_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='basedatos.Catalogo')),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id_presion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'informacion_general',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('loc_codigo', models.CharField(max_length=3)),
                ('loc_descripcion', models.CharField(max_length=150)),
                ('loc_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='basedatos.Localidad')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
    ]
