# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0002_catalogo_informacion_localidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacion',
            old_name='id_presion',
            new_name='id_informacion',
        ),
    ]
